version: '3'
services:
  db:
    image: mysql
    container_name: project_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./sqldb:/var/lib/mysql 
  jupyter:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-jupyter
    container_name: project_jupyter
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
      - ./jupyter_code:/home/jovyan/project
    command: start.sh jupyter notebook --NotebookApp.token=''


