FROM jupyter/base-notebook

USER root

RUN apt-get update

RUN apt-get install -y --no-install-recommends \
    wget \
    xvfb \
    libgtk2.0-0 \
    libxtst6 \
    libxss1 \
    libgconf-2-4 \
    libnss3 \
    libasound2 && \
    mkdir -p /home/orca && \
    cd /home/orca && \
    wget https://github.com/plotly/orca/releases/download/v1.2.1/orca-1.2.1-x86_64.AppImage && \
    chmod +x orca-1.2.1-x86_64.AppImage && \
    ./orca-1.2.1-x86_64.AppImage --appimage-extract && \
    printf '#!/bin/bash \nxvfb-run --auto-servernum --server-args "-screen 0 640x480x24" /home/orca/squashfs-root/app/orca "$@"' > /usr/bin/orca && \
    chmod +x /usr/bin/orca


RUN pip install PyMYSQL pandas mysql.connector datetime numpy plotly requests flask

RUN conda install -c plotly plotly-orca

RUN conda install psutil
